Network ios
ruuvi/station.localization pull request #18
Opened 2021-02-23 06:31 UTC by viikufa

2021-02-23 06:39 UTC, rinat-enikeev requested changes

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "Войдя в сеть вы сможете сохранить свои данные в облаке:\\n- список датчиков\\n- названия датчиков",
comma

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "Зарегистрируйтесь или получите ссылку для входа",
are you sure?

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "en": "Forbiden",
Forbidden

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "en": "Share count is reached",
share limit?

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "en": "Sensor share count is reached",
limit?

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "Нет данных для того чтобы поделиться сенсором",
comma

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "en": "This sensor already is shared",
is already shared

2021-02-23 06:39 UTC, rinat-enikeev commented on station.localization.json
> +      "en": "Invalid mac address",
MAC

2021-02-23 07:26 UTC, andreevdenis commented on station.localization.json
> +      "ru": "Войдя в сеть вы сможете сохранить свои данные в облаке:\\n- список датчиков\\n- названия датчиков",
English text was changed significantly here:

![photo_2021-02-23_10-24-46](https://user-images.githubusercontent.com/24788772/108813143-78c13d00-75c1-11eb-86a7-c7e093785f3b.jpg)

2021-02-23 07:58 UTC, viikufa commented on station.localization.json
> +      "ru": "Зарегистрируйтесь или получите ссылку для входа",
nope, incorrect resolved merge conflict

2021-02-24 07:54 UTC, rinat-enikeev requested changes

2021-02-24 07:54 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "Пожалуйста проверьте email для дальнейших инструкций",
comma

2021-02-24 07:54 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "После входа в систему вы будете автоматически отмечены как владелец ближайших датчиков Ruuvi. Заявленные датчики будут восстановлены после повторной установки приложения. \\n\\nС помощью
we are using "сенсор" everywhere, let's use it here too @andreevdenis ?

2021-02-24 07:54 UTC, rinat-enikeev commented on station.localization.json
> +      "ru": "Пожалуйста проверьте email для дальнейших инструкций",
https://russkiiyazyk.ru/punktuatsiya/pozhaluista-vyideliaetsia-zapiatymi.html

2021-02-24 11:25 UTC, andreevdenis commented on station.localization.json
> +      "ru": "После входа в систему вы будете автоматически отмечены как владелец ближайших датчиков Ruuvi. Заявленные датчики будут восстановлены после повторной установки приложения. \\n\\nС помощью
I agree

2021-02-24 16:37 UTC, rinat-enikeev approved these changes

2021-02-27 12:33 UTC, merged