Station localisation updated missing translations
ruuvi/station.localization pull request #240
Opened 2024-07-11 08:51 UTC by markoaamunkajo

This file is test and done with ChatGPT

2024-07-16 17:56 UTC, andreevdenis commented on station.localization.json
> +      "pl": ""
I noticed some changes in the begining of the each PL string. Tabs changes to spaces or something like this?

2024-07-16 17:56 UTC, andreevdenis commented on station.localization.json
> +      "ru": "Пример перевода",
"Translation example"

2024-07-16 17:56 UTC, andreevdenis commented on station.localization.json
> +      "ru": "Пример перевода",
"Translation example"

2024-07-16 17:57 UTC, andreevdenis commented on station.localization.json
> +      "pl": "Ciągłe skanowanie w tle"
Many unnecessary changes in formating

2024-07-16 18:00 UTC, andreevdenis requested changes
Let's remove this kind of translation:
"ru": "Пример перевода",

I can go through RU lines later.

These lines should not be changed at all if no translation is provided:
![image](https://github.com/user-attachments/assets/5f094642-34f1-49fb-a9a2-481ac8af286a)

2024-08-20 04:27 UTC, markoaamunkajo commented
Not implemented at this point, will close this pull request

2024-08-20 04:27 UTC, closed without merging